name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "4768e5b7237143768ac452baede178a2" },
  { binding = "SHARE", id = "184c0894585841dcb251386594bbaa88" }
]